Read BLS program
NeighborhoodInfoDC/BLS pull request #4
Opened 2019-02-21 21:20 UTC by rpitingolo

@ptatian can you review, please? The program reads in BLS data for the entire country. It might also be a good idea to read-in a subsetted county file just for the DC region. It would be an easy edit if you think so.  Thanks.

2019-02-22 15:25 UTC, ptatian commented
Thanks, @rpitingolo. Reviewing this now.

2019-02-22 15:55 UTC, ptatian requested changes
Thanks, @rpitingolo. A few changes requested. Please let me know if you have questions.

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +%let droplist = Annual_Average_Status_Code;
Why are we dropping this variable? Please include an explanatory comment.

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +		Employment_Location_Quotient_Rel = "1-character location-quotient disclosure code (either '' (blank) or 'N' not disclosed)"
The label says *Employment_Location_Quotient_Rel* is a 1-character code, but this is actually a numeric variable that has a range of values. Is the description of the variable wrong?

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +  out=BLSallyears,
I agree with you that we may want to have one or more different versions of this data set (or perhaps separate data views) that, for instance, has the county-level data for the Washington MSA. In that case, the data set name and data set label should be structured with that in mind. This version is a national data set with all summary levels and the name and label should convey that.

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +		if area_type = "County" then do;
Glad that you created these two vars. :+1:

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +**************************************************************************/
For metadata purposes, we should create and assign permanent formats for the categorical variables *area_type* *own*, and *NAICS*. 

I don't think you need to recode the *area_type* var. Just make the format label identical to the value.

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +		Annual_Average_Establishment_Cou = "Annual average of quarterly establishment counts for a given year"
The var *Annual_Average_Employment* is not labeled.

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +		Cnty "3-character�County FIPS code"
You omitted an = here.

2019-02-22 15:55 UTC, ptatian commented on prog/Read BLS.sas
> +
Yes, so why don't we just go ahead here and create the Washington MSA county file. I would just subset the previous file, either as a new data set or a data view, and then do a second %Finalize_data_set() invocation.

2019-02-22 18:55 UTC, rpitingolo commented on prog/Read BLS.sas
> +%let droplist = Annual_Average_Status_Code;
This variable was causing a numberic/character mismatch error. In most years it's missing for all observations (and coded as numeric). I couldn't figure out an easy to  way to convert it to missing character only in the years when it's completely missing. Do you know of any examples where we have done something like this?

2019-02-22 18:57 UTC, rpitingolo commented on prog/Read BLS.sas
> +		Employment_Location_Quotient_Rel = "1-character location-quotient disclosure code (either '' (blank) or 'N' not disclosed)"
Label is wrong. I updated it.

2019-02-22 19:45 UTC, ptatian commented on prog/Read BLS.sas
> +%let droplist = Annual_Average_Status_Code;
I see. So, it is inconsistent in the various input data sets? That is very annoying. 

Did you try declaring the variable as character by adding a **length** statement before the **set**? That may force it to be read in as character always.

2019-02-22 19:50 UTC, rpitingolo commented on prog/Read BLS.sas
> +%let droplist = Annual_Average_Status_Code;
@ptatian yes I tried using the length statement but still go the 'Variable Annual_Average_Status_Code has been defined as both character and numeric.' error. 

The only thing I can think to do is use data steps and a macro to convert it always to character.

2019-02-22 19:58 UTC, ptatian commented on prog/Read BLS.sas
> +%let droplist = Annual_Average_Status_Code;
@rpitingolo Yes, I guess that doesn't work with converting types. I did some searching but it seems the only way to address this is rename the variable that is of the wrong type and then assign those values to the variable of the correct type. Actually, in this case, if the variable is numeric because it's always missing, then you just need to drop it from those data sets with a drop= option. SAS will automatically assign missing character values to obs coming from those data sets.

2019-02-22 20:54 UTC, rpitingolo commented on prog/Read BLS.sas
> +%let droplist = Annual_Average_Status_Code;
@ptatian OK, I went ahead and used a macro loop to address it. This variable is no longer dropped.

2019-02-22 20:55 UTC, rpitingolo commented
@ptatian Please take another look. You will get format errors but I believe this will be resolved once we batch submit the new formats program.

2019-02-22 22:18 UTC, ptatian requested changes
@rpitingolo More comments

2019-02-22 22:18 UTC, ptatian commented on prog/BLS Formats.sas
> +  FmtName=$naics6,
You can't end a format name with a number.

2019-02-22 22:18 UTC, ptatian commented on prog/BLS Formats.sas
> +  Desc=QCEW Industry Codes and Titles (For NAICS Coded Data),
desc= value must be a quoted character string

2019-02-22 22:18 UTC, ptatian commented on prog/BLS Formats.sas
> +  OtherLabel='',
Value for OtherLabel= should be blank (not empty quotes). Empty quotes is an actual label; blank means don't assign an other label.

2019-02-22 22:18 UTC, ptatian commented on prog/Read BLS.sas
> +%let end_yr = 2017;
I'm not sure what happened, but in the output data set Year is always 2003.

2019-02-25 12:57 UTC, rpitingolo commented on prog/BLS Formats.sas
> +  FmtName=$naics6,
OK thanks. I didn't realize that.

2019-02-25 13:16 UTC, rpitingolo commented
@ptatian addressed the outstanding issues. If this is OK to finalize I will work on producing the indicators we need. Thanks.

2019-02-25 16:46 UTC, ptatian approved these changes

2019-02-25 16:47 UTC, ptatian commented
Thanks, @rpitingolo. I pushed one last syntax correction. It's ready to finalize.

2019-02-25 17:36 UTC, rpitingolo commented
@ptatian thanks. I misunderstood quoted character string.

2019-02-25 17:36 UTC, merged